---
- name: generate and install DNS configuration file
  hosts:
    - all
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  vars:
    tmp_dir: "tmp"
    conf_file: "{{ tmp_dir }}/{{ inventory_hostname }}.conf"
    dns1: "8.8.8.8"
    dns2: "8.8.4.4"

  tasks:
    - debug: var=tmp_dir

    - debug: var=conf_file

    - name: confirm or create configs directory
      file: 
        path: "{{ tmp_dir }}"
        state: directory
      run_once: yes
    
    - name: save device information using template
      template:
        src: template/base-settings.j2
        dest: "{{ conf_file }}"    

    - name: install generated configuration file
      juniper_junos_config:
        provider:
          host: "{{ ansible_host }}"
          port: "22"
          timeout: 120
        src: "{{ conf_file }}"
        load: merge 
        comment: "playbook base-settings.yaml"
        diff: yes
      register: config_results

    - name: show configuration changes
      debug:
        var: config_results.diff_lines
      when: config_results.diff_lines is defined

    - name: delete generated configuration file
      file:
        path: "{{ conf_file }}"
        state: absent
