---
- name: generate and install DNS configuration file
  hosts:
    - all
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  vars:
    tmp_dir: "tmp"
    conf_file: "{{ tmp_dir }}/{{ inventory_hostname }}.conf"
    dns1: "8.8.8.8"
    dns2: "8.8.4.4"
    connection_settings:
      host: "{{ ansible_host }}"
      port: "22"
      timeout: 120

  tasks:
    - name: confirm or create configs directory
      file: 
        path: "{{ tmp_dir }}"
        state: directory
      run_once: yes
    
    - name: save device information using template
      template:
        src: template/base-settings.j2
        dest: "{{ conf_file }}"    

    - name: install generated configuration file
      juniper_junos_config:
        provider: "{{ connection_settings }}"
        src: "{{ conf_file }}"
        load: merge 
        comment: "playbook base-settings.yaml"
        confirmed: 5
        diff: yes
        ignore_warning: yes
      register: config_results
      notify: confirm previous commit

    - name: show configuration changes
      debug:
        var: config_results.diff_lines
      when: config_results.diff_lines is defined

    - name: delete generated configuration file
      file:
        path: "{{ conf_file }}"
        state: absent

  handlers:
    - name: confirm previous commit
      juniper_junos_config: 
        provider:  "{{ connection_settings }}"
        comment: "playbook base-settings.yaml, confirming previous commit"
        commit: yes
        diff: no
